version: "3"

services:
  api:
    build: .
    image: "api"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - .env.docker:/app/.env
    command: bash -c "nodemon server.js"
  mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
volumes:
  mongodb:
    driver: local
